// src/data.js
// Datos de ejemplo de películas y series estilo Netflix

export const items = [
  {
    id: 1,
    title: 'Stranger Things',
    type: 'serie',
    description: 'Un grupo de niños se enfrenta a fuerzas sobrenaturales en su ciudad.',
    image: 'https://image.tmdb.org/t/p/w1280/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg',
  },
  {
    id: 2,
    title: 'La Casa de Papel',
    type: 'serie',
    description: 'Un grupo de ladrones lleva a cabo el mayor atraco de la historia.',
    image: 'https://image.tmdb.org/t/p/w1280/mo0FP1GxOFZT4UDde7RFDz5APXF.jpg',
  },
  {
    id: 3,
    title: 'El Irlandés',
    type: 'pelicula',
    description: 'Un asesino a sueldo recuerda su pasado en la mafia.',
    image: 'https://image.tmdb.org/t/p/w1280/mbm8k3GFhXS0ROd9AD1gqYbIFbM.jpg',
  },
  {
    id: 4,
    title: 'Enola Holmes',
    type: 'pelicula',
    description: 'La hermana menor de Sherlock Holmes resuelve su propio misterio.',
    image: 'https://image.tmdb.org/t/p/w1280/riYInlsq2kf1AWoGm80JQW5dLKp.jpg',
  },
  {
    id: 5,
    title: 'The Witcher',
    type: 'serie',
    description: 'Un cazador de monstruos lucha por encontrar su lugar en un mundo lleno de bestias.',
    image: 'https://image.tmdb.org/t/p/w1280/7vjaCdMw15FEbXyLQTVa04URsPm.jpg',
  },
  {
    id: 6,
    title: 'Bird Box',
    type: 'pelicula',
    description: 'Una madre y sus hijos luchan por sobrevivir en un mundo postapocalíptico.',
    image: 'https://image.tmdb.org/t/p/w1280/3r1C9hGq0bX9oFf5vN2V8rT2kK9.jpg',
  },
  {
    id: 7,
    title: 'Breaking Bad',
    type: 'serie',
    description: 'Un profesor de química se convierte en fabricante de metanfetamina.',
    image: 'https://image.tmdb.org/t/p/w1280/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
  },
  {
    id: 8,
    title: 'Dark',
    type: 'serie',
    description: 'Cuatro familias descubren un misterio que abarca varias generaciones.',
    image: 'https://image.tmdb.org/t/p/w1280/3LTPbD0jzLDR5G0gWnQ1gG1XkT1.jpg',
  },
  {
    id: 9,
    title: 'Extraction',
    type: 'pelicula',
    description: 'Un mercenario se embarca en una misión peligrosa para rescatar a un niño.',
    image: 'https://image.tmdb.org/t/p/w1280/wlfDxbGEsW58vGhFljKkcR5IxDj.jpg',
  },
  {
    id: 10,
    title: 'Narcos',
    type: 'serie',
    description: 'La historia real de los cárteles de droga en Colombia.',
    image: 'https://image.tmdb.org/t/p/w1280/rTmal9fDbwh5F0waol2hq35U4ah.jpg',
  },
  {
    id: 11,
    title: 'Red Notice',
    type: 'pelicula',
    description: 'Un agente del FBI y dos criminales unen fuerzas en una aventura internacional.',
    image: 'https://image.tmdb.org/t/p/w1280/lAXONuqg41NwUMuzMiFvicDET9Y.jpg',
  },
  {
    id: 12,
    title: 'Lupin',
    type: 'serie',
    description: 'Un ladrón de guante blanco inspirado en Arsène Lupin.',
    image: 'https://image.tmdb.org/t/p/w1280/sgxawbFB5Vi5OkPWQLNfl3dvkNJ.jpg',
  },
  {
    id: 13,
    title: 'Dark',
    type: 'serie',
    description: 'Misteriosas desapariciones revelan secretos ocultos en un pueblo alemán.',
    image: 'https://image.tmdb.org/t/p/w500/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg',
  },
  {
    id: 15,
    title: 'Roma',
    type: 'pelicula',
    description: 'Una empleada doméstica vive los cambios sociales y familiares en el México de los 70.',
    image: 'https://image.tmdb.org/t/p/w500/yuPotujxKrpGEx4QnN0P4f9QO5t.jpg',
  },
  {
    id: 16,
    title: 'BoJack Horseman',
    type: 'serie',
    description: 'Un actor fracasado y alcohólico, que además es un caballo, intenta redimirse.',
    image: 'https://image.tmdb.org/t/p/w500/zGVbrulkupqpbwgiNedkJPyQum4.jpg',
  },
  {
    id: 17,
    title: 'Extraction',
    type: 'pelicula',
    description: 'Un mercenario se embarca en una peligrosa misión para rescatar a un niño secuestrado.',
    image: 'https://image.tmdb.org/t/p/w500/wlfDxbGEsW58vGhFljKkcR5IxDj.jpg',
  },
  {
    id: 18,
    title: 'Cobra Kai',
    type: 'serie',
    description: 'Décadas después del torneo, Johnny y Daniel reavivan su rivalidad en una nueva generación.',
    image: 'https://image.tmdb.org/t/p/w500/6POBWybSBDBKjSs1VAQcnQC1qyt.jpg',
  },
  {
    id: 19,
    title: 'El Camino: Una película de Breaking Bad',
    type: 'pelicula',
    description: 'Jesse Pinkman huye de la policía mientras intenta escapar de su pasado.',
    image: 'https://image.tmdb.org/t/p/w500/9O7gLzmreU0nGkIB6K3BsJbzvNv.jpg',
  },
  {
    id: 20,
    title: 'Black Mirror',
    type: 'serie',
    description: 'Cada episodio explora una historia independiente sobre tecnología y consecuencias sociales.',
    image: 'https://image.tmdb.org/t/p/w500/pX1F4JMRRQnICv41P2df4H24Pnl.jpg',
  },
  {
    id: 21,
    title: 'Red Notice',
    type: 'pelicula',
    description: 'Un agente del FBI se une a un ladrón para atrapar a otro criminal más buscado.',
    image: 'https://image.tmdb.org/t/p/w500/lAXONuqg41NwUMuzMiFvicDET9Y.jpg',
  },
  {
    id: 22,
    title: 'You',
    type: 'serie',
    description: 'Un joven aparentemente encantador esconde una peligrosa obsesión con el amor.',
    image: 'https://image.tmdb.org/t/p/w500/lnWkyG3LLgbbrIEeyl5mK5VRFe4.jpg',
  },
];
